services:

  nginx:
    build: ./frontend
    container_name: nginx_proxy
    restart: "no"
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
        - VITE_API_URL=http://backend:4000/graphql
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - type: tmpfs
        target: /var/log/nginx

# #! Importante. Os dados aqui serão apagdos após a execução.
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydatabase"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_server
    restart: "no"
    environment:
      DATABASE_URL: "postgresql://admin:secret@postgres:5432/mydatabase"
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy

  e2e-tests:
    build: ./e2e
    restart: "no"
    container_name: e2e-tests
    working_dir: /app
    depends_on:
      - backend
      - nginx
    environment:
      - ROD_BROWSER_BIN=/usr/bin/chromium
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=mydatabase
    volumes:
      - ./e2e:/app
      - ./backend:/backend
      - ./frontend:/frontend
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "
      go test -v /app/main_test.go | tee /app/e2e_main.log && sleep 3 &&
      go test -v /app/tests/... | tee /app/e2e.log;
      test $${?} -eq 0"

  mock-api:
    container_name: CoinGecko
    build: ./CoinGecko
    ports:
      - "8082:8082"
